apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "23"
  creationTimestamp: "2020-01-02T19:21:13Z"
  generation: 39
  labels:
    app: grafana
  name: grafana
  namespace: default
  resourceVersion: "30833940"
  selfLink: /apis/apps/v1/namespaces/default/deployments/grafana
  uid: 0a571458-2d95-11ea-b5f8-42010a80007c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grafana
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grafana
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: grafana-creds
        image: monitoringartist/grafana-xxl
        imagePullPolicy: Always
        name: grafana
        resources: {}
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-data
        - mountPath: /etc/grafana/provisioning/datasources/influxdb-datasource.yml
          name: grafana-config
          readOnly: true
          subPath: influxdb-datasource.yml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana-pvc
      - configMap:
          defaultMode: 420
          name: grafana-config
        name: grafana-config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-02-18T15:53:13Z"
    lastUpdateTime: "2020-02-18T15:53:13Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-01-02T19:21:13Z"
    lastUpdateTime: "2020-02-21T18:31:37Z"
    message: ReplicaSet "grafana-5949cffc55" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 39
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
