apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "24"
  creationTimestamp: "2020-03-05T14:52:29Z"
  generation: 26
  labels:
    app: opc-server
  name: opc-server
  namespace: default
  resourceVersion: "37230083"
  selfLink: /apis/apps/v1/namespaces/default/deployments/opc-server
  uid: efab4fb5-5ef0-11ea-a9a4-42010a8001d2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: opc-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: opc-server
    spec:
      containers:
      - image: mjkl/node-opcua-logger
        imagePullPolicy: Always
        name: opc-plc
        resources: {}
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/node/app/config.toml
          name: config-opc
          readOnly: true
          subPath: config.toml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: config-opc
        name: config-opc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-11T15:28:51Z"
    lastUpdateTime: "2020-03-11T15:40:54Z"
    message: ReplicaSet "opc-server-56958df4d6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-03-11T16:14:41Z"
    lastUpdateTime: "2020-03-11T16:14:41Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 26
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
