apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "16"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"telegraf-deployment","namespace":"default"},"spec":{"minReadySeconds":5,"selector":{"matchLabels":{"app":"telegraf"}},"template":{"metadata":{"labels":{"app":"telegraf"}},"spec":{"containers":[{"envFrom":[{"secretRef":{"name":"telegraf-secrets"}}],"image":"telegraf:latest","name":"telegraf","volumeMounts":[{"mountPath":"/etc/telegraf/telegraf.conf","name":"telegraf-config","readOnly":true,"subPath":"telegraf.conf"}]}],"volumes":[{"configMap":{"name":"telegraf-config"},"name":"telegraf-config"}]}}}}
  creationTimestamp: "2020-01-13T14:21:54Z"
  generation: 98
  name: telegraf-deployment
  namespace: default
  resourceVersion: "29852189"
  selfLink: /apis/apps/v1/namespaces/default/deployments/telegraf-deployment
  uid: 0cab3c49-3610-11ea-b5f8-42010a80007c
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: telegraf
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: telegraf
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: telegraf-secrets
        image: telegraf:latest
        imagePullPolicy: Always
        name: telegraf
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /pvcfilesuploaded
          name: nfs-pvc
        - mountPath: /etc/telegraf/telegraf.conf
          name: telegraf-config
          subPath: telegraf.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs-pvc
        persistentVolumeClaim:
          claimName: nfs
      - configMap:
          defaultMode: 420
          name: telegraf-config
        name: telegraf-config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-01-17T16:28:07Z"
    lastUpdateTime: "2020-01-27T20:35:06Z"
    message: ReplicaSet "telegraf-deployment-8d8d8c8fd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-02-18T20:47:52Z"
    lastUpdateTime: "2020-02-18T20:47:52Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 98
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
