apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-01-02T19:19:23Z"
  labels:
    app: influxdb
    project: demo
  name: influxdb
  namespace: default
  resourceVersion: "13944689"
  selfLink: /api/v1/namespaces/default/services/influxdb
  uid: c8dfe506-2d94-11ea-b5f8-42010a80007c
spec:
  clusterIP: 10.11.253.180
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: influxdb
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
