apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"nfs-server","namespace":"default"},"spec":{"ports":[{"name":"nfs","port":2049},{"name":"mountd","port":20048},{"name":"rpcbind","port":111}],"selector":{"role":"nfs-server"}}}
  creationTimestamp: "2020-01-27T16:06:55Z"
  name: nfs-server
  namespace: default
  resourceVersion: "22356472"
  selfLink: /api/v1/namespaces/default/services/nfs-server
  uid: 09d35df3-411f-11ea-b184-42010a800163
spec:
  clusterIP: 10.11.254.207
  ports:
  - name: nfs
    port: 2049
    protocol: TCP
    targetPort: 2049
  - name: mountd
    port: 20048
    protocol: TCP
    targetPort: 20048
  - name: rpcbind
    port: 111
    protocol: TCP
    targetPort: 111
  selector:
    role: nfs-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}