apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  creationTimestamp: "2019-12-28T21:59:46Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    name: grafana
  name: grafana-config-grafana-0
  namespace: monitoring
  resourceVersion: "12260268"
  selfLink: /api/v1/namespaces/monitoring/persistentvolumeclaims/grafana-config-grafana-0
  uid: 5c6c99c0-29bd-11ea-b5f8-42010a80007c
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 200Mi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-5c6c99c0-29bd-11ea-b5f8-42010a80007c
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound