apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"app":"influxdb","project":"twittergraph"},"name":"influxdb","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"2Gi"}}}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  creationTimestamp: "2020-01-02T18:39:48Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: influxdb
    project: twittergraph
  name: influxdb
  namespace: default
  resourceVersion: "13935375"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/influxdb
  uid: 40ddbea1-2d8f-11ea-b5f8-42010a80007c
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-40ddbea1-2d8f-11ea-b5f8-42010a80007c
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  phase: Bound
